title: <span style="color: red;">Version 1.0</span>
logo: /images/github_profile_photo.png
description: University of Bath Graduate with First Class Honours Majoring in Physics
theme: jekyll-theme-minimal


